version: "3"

server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=${PORT:-8080}"

http:
  address: 0.0.0.0:${PORT:-8080}
  middleware: []
  pool:
    num_workers: 2
    debug: true
    supervisor:
      exec_ttl: 60s
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  channels:
    http:
      level: error
    server:
      level: info
    metrics:
      level: error

reload:
  interval: 1s
  patterns: [".php"]
  services:
    http:
      dirs: ["."]
      recursive: true
